package com.example.kinoxp.model;

public enum Genre {

    ACTION, ADVENTURE, COMEDY, DRAMA, HORROR, THRILLER, SCIENCE_FICTION, FANTASY, ROMANCE, CRIME, MYSTERY, DOCUMENTARY, ANIMATION, FAMILY, WAR, WESTERN, MUSICAL, BIOGRAPHY, HISTORY, SPORT, SUPERHERO;
}
